# Generated by Django 3.1.13 on 2021-11-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybook',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
