# Generated by Django 3.1.13 on 2021-11-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybooks', '0002_auto_20211116_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybook',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW')], default='DEPOSIT', max_length=8),
        ),
    ]
