# Generated by Django 3.1.13 on 2021-11-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybooks', '0003_moneybook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybook',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW')], default='WITHDRAW', max_length=8),
        ),
    ]
