# Generated by Django 3.1.13 on 2021-11-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybooks', '0004_auto_20211117_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybook',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
