# Generated by Django 3.1.13 on 2021-11-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybooks', '0005_auto_20211117_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybook',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
