# Generated by Django 3.1.13 on 2021-11-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybooks', '0006_moneybook_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybook',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
